server:
  port: 8094
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 19pool90
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


